'use client';
import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { api,write,money,day,Page,Row } from '@/lib/api';
import { BookingBadge } from '@/components/marketplace-shell';
import { PageTitle,Loading,ErrorState,Empty,Pager,Modal } from '@/components/ui';
export default function Bookings(){
 const client=useQueryClient();const [status,setStatus]=useState('PENDING_CONFIRMATION');const [page,setPage]=useState(1);const [selected,setSelected]=useState<Row|null>(null);const [historyId,setHistoryId]=useState('');const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);
 const path='/bookings?status='+status+'&page='+page;
 const rows=useQuery({queryKey:[path],queryFn:()=>api<Page>(path),refetchInterval:30000});
 const history=useQuery({queryKey:['booking-history',historyId],queryFn:()=>api<Row[]>('/bookings/'+historyId+'/history'),enabled:!!historyId});
 return <><PageTitle title="Booking confirmations" description="Check availability and the final inclusive total before confirming a guest's plans."/><div className="market-categories">{['PENDING_CONFIRMATION','RECONFIRMING','CHANGE_REQUESTED','CONFIRMED','REJECTED','PLANNED',''].map(value=><button key={value} className={value===status?'selected':''} onClick={()=>{setStatus(value);setPage(1);}}>{value?value.replaceAll('_',' '):'ALL BOOKINGS'}</button>)}</div>{rows.isPending?<Loading/>:rows.error?<ErrorState error={rows.error}/>:!rows.data?.items.length?<Empty title="All caught up" description="Booking requests matching this status will appear here."/>:<div className="booking-queue">{rows.data.items.map(item=><article key={item.Id} className="booking-queue-card"><div><BookingBadge status={item.EffectiveStatus||item.BookingStatus}/><h2>{item.Activity}</h2><p>{item.CustomerName} / {item.TripName}</p><p>{day(item.EventDate)} at {item.EventTime} / {item.PartySize} guests / Quantity {item.Quantity}</p><p>{item.VendorName||'Island One concierge'}{item.ConfirmedPrice!=null?' / '+money(item.ConfirmedPrice):''}</p>{item.Pickup&&<p>Pickup: {item.Pickup}</p>}{item.Dropoff&&<p>Drop-off: {item.Dropoff}</p>}<p>{item.Notes}</p></div><div className="booking-queue-actions"><button className="button secondary" onClick={()=>setHistoryId(item.Id)}>View history</button>{!['CANCELLED','COMPLETED'].includes(item.BookingStatus)&&<button className="button" onClick={()=>{setSelected({...item,BookingStatus:item.EffectiveStatus||item.BookingStatus});setError(null);}}>Review booking</button>}</div></article>)}</div>}{rows.data&&<Pager data={rows.data} onPage={setPage}/>}
 {selected&&<Modal title={'Review '+selected.Activity} onClose={()=>setSelected(null)}><form className="resource-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);const form=new FormData(e.currentTarget);const next=String(form.get('status'));const body:Row={Version:selected.Version,Status:next,Notes:String(form.get('reason')||'')};if(next==='CONFIRMED'){body.ConfirmedPrice=String(form.get('price'));body.ConfirmationReference=String(form.get('reference'));body.ConfirmationConditions=String(form.get('conditions')||'');if(form.get('expiry'))body.ConfirmationExpiresAt=new Date(String(form.get('expiry'))).toISOString();}try{await write('/bookings/'+selected.Id+'/status',body,'PATCH');await client.invalidateQueries();setSelected(null);}catch(err){setError(err as Error);}finally{setBusy(false);}}}><div className="form-grid"><label>Action<select name="status" required defaultValue={['PLANNED','REJECTED','EXPIRED'].includes(selected.BookingStatus)?'PENDING_CONFIRMATION':selected.BookingStatus==='CONFIRMED'?'COMPLETED':'CONFIRMED'}>{['PLANNED','REJECTED','EXPIRED'].includes(selected.BookingStatus)?<option value="PENDING_CONFIRMATION">Submit for confirmation</option>:selected.BookingStatus==='CONFIRMED'?<option value="COMPLETED">Mark completed</option>:<><option value="CONFIRMED">Confirm availability and price</option><option value="REJECTED">Reject - unavailable</option></>}<option value="CANCELLED">Cancel booking</option></select></label><label>Final inclusive total (USD)<input name="price" type="number" min="0.01" step="0.01" defaultValue={selected.ConfirmedPrice||''}/></label><label>Confirmation reference<input name="reference" maxLength={160} defaultValue={selected.ConfirmationReference||''}/></label><label>Confirmation expiry (your local time)<input name="expiry" type="datetime-local"/></label><label className="wide">Confirmation conditions<textarea name="conditions" maxLength={2000}/></label><label className="wide">Reason / notes<textarea name="reason" maxLength={2000}/></label></div>{error&&<ErrorState error={error}/>}<button className="button" disabled={busy}>{busy?'Saving...':'Save booking decision'}</button></form></Modal>}
 {historyId&&<Modal title="Booking history" onClose={()=>setHistoryId('')}>{history.isPending?<Loading/>:history.error?<ErrorState error={history.error}/>:history.data?.map(h=><article key={h.Id} className="history-entry"><BookingBadge status={h.NewStatus}/><p>{h.Notes}</p><small>{h.ActorName} / {new Date(h.CreatedAt).toLocaleString()}</small><details><summary>Booking details at this change</summary><pre>{JSON.stringify(JSON.parse(h.Snapshot),null,2)}</pre></details></article>)}</Modal>}</>;
}