'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight,Plus,Search,Clock3,Compass,Pencil,Star } from 'lucide-react';
import { api,Page,Row,can,money } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { PageTitle,Panel,Modal,Form,Field,Pager,Empty,Loading,ErrorState,Back } from '@/components/ui';
const categoryFields:Field[]=[{name:'Name',label:'Category name',required:true,max:120},{name:'DisplayOrder',label:'Display order',type:'number',min:0,max:10000},{name:'Description',label:'Description',type:'textarea',max:1000},{name:'Active',label:'Available to guests',type:'checkbox'}];
const serviceFields:Field[]=[
 {name:'Destination',label:'Destination',required:true,max:100},{name:'Location',label:'Location',max:300},{name:'VendorId',label:'Supplier',source:'/vendors'},
 {name:'Published',label:'Published in marketplace',type:'checkbox'},{name:'Bookable',label:'Accept booking requests',type:'checkbox'},
 {name:'Image',label:'Photos',type:'photos',wide:true},{name:'Amenities',label:'Features / amenities',type:'textarea'},
 {name:'BookingRequirements',label:'Booking requirements',type:'textarea'},{name:'CancellationPolicy',label:'Cancellation policy',type:'textarea'},{name:'AvailabilityNotes',label:'Availability information',type:'textarea',max:1000},
 {name:'Name',label:'Experience name',required:true,max:160},{name:'CategoryId',label:'Category',source:'/service-categories?all=true',required:true},
 {name:'ShortDescription',label:'A short introduction',type:'textarea',required:true,max:300},{name:'Description',label:'The full experience',type:'textarea',required:true,max:12000},
 {name:'StartingPrice',label:'Starting price (USD)',type:'number',min:0,step:'0.01'},{name:'PricingType',label:'Pricing',type:'select',required:true,options:['Fixed','Starting From','Per Person','Per Hour','Custom Quote'].map(x=>({label:x,value:x}))},
 {name:'Duration',label:'Duration',max:100},
 {name:'DisplayOrder',label:'Display order',type:'number',min:0,max:10000},{name:'Active',label:'Available to guests',type:'checkbox'},{name:'Featured',label:'Featured experience',type:'checkbox'},{name:'Options',label:'Available options',type:'options'}
];
export default function Catalog({mode,id}:{mode:string;id?:string}){
 const {data:a}=useActor();const admin=can(a,'catalog.write');const categories=mode==='categories';
 const [page,setPage]=useState(1);const [category,setCategory]=useState('');const [search,setSearch]=useState('');const [editing,setEditing]=useState<Row|null>(null);
 const listPath=(categories?'/service-categories':'/services')+'?page='+page+'&search='+encodeURIComponent(search)+'&categoryId='+category+(admin?'&all=true':'');
 const list=useQuery({queryKey:[listPath],queryFn:()=>api<Page>(listPath),enabled:!id});
 const cats=useQuery({queryKey:['catalog-categories'],queryFn:()=>api<Page>('/service-categories?limit=100'),enabled:!categories});
 const detail=useQuery({queryKey:['service',id],queryFn:()=>api<Row>('/services/'+id),enabled:!!id});
 const [requesting,setRequesting]=useState(false);
 const item=detail.data;
 const modal=editing&&<Modal title={editing.Id?'Refine the details':categories?'A new category':'A new experience'} onClose={()=>setEditing(null)}><Form fields={categories?categoryFields:serviceFields} initial={editing} endpoint={(categories?'/service-categories':'/services')+(editing.Id?'/'+editing.Id:'')} method={editing.Id?'PATCH':'POST'} onSuccess={()=>setEditing(null)} submit={editing.Id?'Save experience':'Create '+(categories?'category':'experience')}/></Modal>;
 if(id){
  if(detail.isPending)return <Loading/>;if(detail.error)return <ErrorState error={detail.error}/>;
  return <><Back href="/services">All experiences</Back><div className="service-detail"><div className="service-detail-image"><Image src={item!.Image||'/images/coast.svg'} alt={item!.Name} fill priority sizes="(max-width: 900px) 100vw, 60vw"/><span className="image-caption">THE BAHAMAS · PERSONALLY ARRANGED</span></div><div className="service-detail-copy"><p className="eyebrow">{item!.CategoryName}</p><h1>{item!.Name}</h1><p className="intro">{item!.ShortDescription}</p><div className="detail-price">{money(item!.StartingPrice)}<small>{item!.PricingType}</small></div><div className="service-meta"><Clock3 size={16}/>{item!.Duration||'Tailored to your day'}</div><p className="detail-description">{item!.Description}</p>{item!.Options?.length>0&&<div className="service-options"><h3>Make it yours</h3>{item!.Options.map((o:Row)=><div key={o.Id}><span>{o.Name}<small>{o.Description}</small></span><strong>{o.Price?money(o.Price):'Personalised'}</strong></div>)}</div>}<button className="button full" onClick={()=>setRequesting(true)}>Request this experience <ArrowUpRight size={17}/></button><p className="booking-note">Your concierge will confirm availability and the final details with you.</p>{admin&&<button className="text-button" onClick={()=>setEditing(item!)}><Pencil size={15}/> Edit experience</button>}</div></div>{modal}{requesting&&<Modal title="A little more about your plans" onClose={()=>setRequesting(false)}><p className="muted">{item!.Name} · All times are local to The Bahamas.</p><Form endpoint="/service-requests" extra={{ServiceId:id}} fields={[{name:'TripId',label:'Trip',source:'/trips',required:true},{name:'PreferredDate',label:'Preferred date',type:'date',required:true},{name:'PreferredTime',label:'Preferred time',type:'time',required:true},{name:'Guests',label:'Number of guests',type:'number',min:1,max:200,required:true},...(item!.Options.length?[{name:'OptionId',label:'Experience option',type:'select',options:item!.Options.map((o:Row)=>({label:o.Name,value:o.Id}))}]:[]),{name:'SpecialRequirements',label:'Anything we should know?',type:'textarea'},{name:'Notes',label:'A note for your concierge',type:'textarea'}]} initial={{Guests:2}} onSuccess={()=>setRequesting(false)} submit="Send my request"/></Modal>}</>;
 }
 return <><PageTitle eyebrow={categories?'CURATE THE COLLECTION':'A LITTLE INSPIRATION'} title={categories?'Experience categories':'Made for your kind of island time.'} description={categories?'Thoughtful organisation for every kind of stay.':'Extraordinary experiences. Personally selected. Seamlessly arranged.'} action={admin&&<button className="button" onClick={()=>setEditing({Active:true,Published:false,Bookable:true,Destination:'Jamaica',DisplayOrder:0,PricingType:'Starting From',Options:[]})}><Plus size={17}/>{categories?'New category':'New experience'}</button>}/>
 {!categories&&<div className="catalog-banner"><Compass size={28}/><div><p className="eyebrow">BEYOND THE EXPECTED</p><h2>There’s a Bahamas experience with your name on it.</h2></div><span>Curated by people who call these islands home.</span></div>}
 <div className="catalog-toolbar"><div className="category-tabs"><button className={!category?'selected':''} onClick={()=>{setCategory('');setPage(1);}}>All experiences</button>{!categories&&cats.data?.items.map(c=><button key={c.Id} className={category===c.Id?'selected':''} onClick={()=>{setCategory(c.Id);setPage(1);}}>{c.Name}</button>)}</div><div className="inline-search"><Search size={16}/><input aria-label="Search experiences" placeholder="Find your experience" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></div>
 {list.isPending?<Loading/>:list.error?<ErrorState error={list.error}/>:!list.data?.items.length?<Empty title={categories?'Begin your collection':'A little more inspiration is on its way'} description={search?'Try another search or category.':'Your concierge will add available experiences here.'}/>:categories?<Panel><div className="category-list">{list.data.items.map(c=><div className="category-row" key={c.Id}><span className="list-icon"><Compass size={19}/></span><div className="grow"><strong>{c.Name}</strong><small>{c.Description||'Display order '+c.DisplayOrder}</small></div><span className={'status '+(c.Active?'status-confirmed':'status-cancelled')}>{c.Active?'Active':'Inactive'}</span><button className="icon-button" aria-label={'Edit '+c.Name} onClick={()=>setEditing(c)}><Pencil size={16}/></button></div>)}</div></Panel>:<div className="service-grid">{list.data.items.map(s=><article className="service-card" key={s.Id}><Link className="service-card-image" href={'/services/'+s.Id}><Image src={s.Image||'/images/coast.svg'} alt={s.Name} fill sizes="(max-width: 700px) 100vw, (max-width: 1200px) 50vw, 33vw"/>{s.Featured&&<span className="featured"><Star size={11}/> CONCIERGE FAVOURITE</span>}{!s.Active&&<span className="inactive-tag">Inactive</span>}</Link><div className="service-card-copy"><p className="eyebrow">{s.CategoryName}</p><Link href={'/services/'+s.Id}><h2>{s.Name}</h2></Link><p>{s.ShortDescription}</p><div className="service-meta"><Clock3 size={14}/>{s.Duration||'At your pace'}</div><div className="service-card-footer"><span><small>{s.PricingType==='Custom Quote'?'PERSONALLY QUOTED':s.PricingType.toUpperCase()}</small><strong>{money(s.StartingPrice)}</strong></span><Link className="round-link" href={'/services/'+s.Id} aria-label={'View '+s.Name}><ArrowUpRight size={19}/></Link></div></div></article>)}</div>}
 {list.data&&<Pager data={list.data} onPage={setPage}/>}<div className="catalog-help"><Message/><span>Something else in mind? <Link href="/messages">Let your concierge make it happen.</Link></span></div>{modal}</>;
}
function Message(){return <Compass size={17}/>;}

