'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { Plus,Search,Mail,Phone,Pencil,ArrowUpRight,Users } from 'lucide-react';
import { api,Page,Row,can,day } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { PageTitle,Panel,Modal,Form,Field,Pager,Empty,Loading,ErrorState,Back,Status } from '@/components/ui';
import Trips from './trips';
export const preferenceFields:Field[]=[{name:'DietaryRequirements',label:'Dietary requirements',type:'textarea',max:1000},{name:'Interests',label:'The things you love',type:'textarea',max:1000},{name:'Transportation',label:'How you like to get around',type:'textarea',max:1000},{name:'Notes',label:'The little things that make a difference',type:'textarea'}];
const createFields:Field[]=[{name:'DisplayName',label:'Full name',required:true,max:120},{name:'Email',label:'Email address',type:'email',required:true,max:254},{name:'Phone',label:'Phone number',max:40},{name:'Password',label:'Initial password',type:'password',required:true,hint:'At least 12 characters. Share securely with the customer.'},{name:'Notes',label:'Customer notes',type:'textarea'}];
function Related({customerId,kind}:{customerId:string;kind:'requests'|'itinerary'}){
 const [page,setPage]=useState(1);const path=(kind==='requests'?'/service-requests':'/itineraries')+'?customerId='+customerId+'&page='+page;
 const q=useQuery({queryKey:[path],queryFn:()=>api<Page>(path)});
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorState error={q.error}/>;
 return <Panel title={kind==='requests'?'Service requests':'Itinerary'}>{q.data?.items.length?q.data.items.map(r=><div className="compact-row" key={r.Id}><div className="grow"><strong>{r.ServiceName||r.Activity}</strong><small>{day(r.PreferredDate||r.EventDate,true)} · {r.PreferredTime||r.EventTime}</small></div>{r.Status&&<Status value={r.Status}/>}<Link className="icon-button" aria-label="View details" href={kind==='requests'?'/requests/'+r.Id:'/itinerary?trip='+r.TripId}><ArrowUpRight size={16}/></Link></div>):<Empty title="No entries yet" description="New experiences will appear here."/>}{q.data&&<Pager data={q.data} onPage={setPage}/>}</Panel>;
}
export default function Customers({id}:{id?:string}){
 const {data:a}=useActor();const edit=can(a,'customers.write');const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [modal,setModal]=useState('');const [tab,setTab]=useState('overview');
 const path='/customers?page='+page+'&search='+encodeURIComponent(search);
 const q=useQuery({queryKey:[path],queryFn:()=>api<Page>(path),enabled:!id});
 const detail=useQuery({queryKey:['customer',id],queryFn:()=>api<Row>('/customers/'+id),enabled:!!id});
 const c=detail.data;
 if(id){
  if(detail.isPending)return <Loading/>;if(detail.error)return <ErrorState error={detail.error}/>;
  return <><Back href="/customers">All customers</Back><PageTitle eyebrow="THE PERSON BEHIND THE PLANS" title={c!.DisplayName} description="A personal view of every preference and experience." action={edit&&<button className="button secondary" onClick={()=>setModal('profile')}><Pencil size={16}/>Edit profile</button>}/><div className="customer-summary"><span className="avatar large">{c!.DisplayName.split(' ').map((s:string)=>s[0]).slice(0,2).join('')}</span><div><h2>{c!.DisplayName}</h2><div className="customer-contact"><span><Mail size={14}/>{c!.Email}</span><span><Phone size={14}/>{c!.Phone||'No phone shared'}</span></div></div><Status value={c!.Status}/></div><div className="page-tabs">{['overview','experiences','requests','itinerary','preferences','guests'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 {tab==='overview'&&<div className="detail-grid"><Panel title="Contact information"><div className="padded"><div className="preference-line"><small>Email</small><p>{c!.Email}</p></div><div className="preference-line"><small>Phone</small><p>{c!.Phone||'Not yet shared'}</p></div><div className="preference-line"><small>Customer notes</small><p>{c!.Notes||'No additional notes.'}</p></div></div></Panel><Panel title="A personal touch"><div className="padded">{preferenceFields.slice(0,3).map(f=><div className="preference-line" key={f.name}><small>{f.label}</small><p>{c!.Preferences[f.name]||'Nothing shared just yet.'}</p></div>)}</div></Panel></div>}
 {tab==='experiences'&&<Trips customerId={id}/>}
 {tab==='requests'&&<Related customerId={id} kind="requests"/>}{tab==='itinerary'&&<Related customerId={id} kind="itinerary"/>}
 {tab==='preferences'&&<Panel title="The details that matter"><div className="padded">{edit?<Form fields={preferenceFields} initial={c!.Preferences} endpoint={'/customers/'+id+'/preferences'} method="PATCH"/>:preferenceFields.map(f=><div className="preference-line" key={f.name}><small>{f.label}</small><p>{c!.Preferences[f.name]||'Not shared'}</p></div>)}</div></Panel>}
 {tab==='guests'&&<Panel title="Their travelling companions" action={edit&&<button className="text-button" onClick={()=>setModal('guest')}><Plus size={15}/>Add guest</button>}>{c!.Guests.length?c!.Guests.map((g:Row)=><div className="compact-row" key={g.Id}><span className="list-icon"><Users size={18}/></span><div><strong>{g.DisplayName}</strong><small>{g.Relationship}{g.Notes?' · '+g.Notes:''}</small></div></div>):<Empty title="A place for their people" description="Travelling companions can be added here."/>}</Panel>}
 {modal&&<Modal title={modal==='guest'?'A travelling companion':'Customer details'} onClose={()=>setModal('')}><Form endpoint={'/customers/'+id+(modal==='guest'?'/guests':'')} method={modal==='guest'?'POST':'PATCH'} fields={modal==='guest'?[{name:'DisplayName',label:'Full name',required:true,max:120},{name:'Relationship',label:'Relationship',max:60},{name:'Notes',label:'Notes',type:'textarea',max:1000}]:[{name:'DisplayName',label:'Full name',required:true,max:120},{name:'Phone',label:'Phone',max:40},{name:'Status',label:'Status',type:'select',options:['Active','Inactive'].map(x=>({label:x,value:x}))},{name:'Notes',label:'Notes',type:'textarea'}]} initial={modal==='guest'?{}:c} onSuccess={()=>setModal('')}/></Modal>}</>;
 }
 return <><PageTitle eyebrow="RELATIONSHIPS, PERSONALLY KEPT" title="Know the guest. Elevate the stay." description="Every preference remembered. Every experience considered." action={edit&&<button className="button" onClick={()=>setModal('new')}><Plus size={17}/>New customer</button>}/><div className="filters"><div className="inline-search"><Search size={17}/><input aria-label="Search customers" placeholder="Find a name or email…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></div>{q.isPending?<Loading/>:q.error?<ErrorState error={q.error}/>:q.data?.items.length?<Panel><div className="data-table customer-table"><div className="table-head"><span>CUSTOMER</span><span>CONTACT</span><span>NEXT EXPERIENCE</span><span>REQUESTS</span><span>STATUS</span><span/></div>{q.data.items.map(c=><Link className="table-row" href={'/customers/'+c.Id} key={c.Id}><div className="name-cell"><span className="avatar">{c.DisplayName.split(' ').map((s:string)=>s[0]).slice(0,2).join('')}</span><strong>{c.DisplayName}</strong></div><div><strong>{c.Email}</strong><small>{c.Phone||'No phone shared'}</small></div><div>{c.UpcomingTrip?day(c.UpcomingTrip,true):'Not yet arranged'}</div><div>{c.ActiveRequests} active</div><Status value={c.Status}/><ArrowUpRight size={16}/></Link>)}</div></Panel>:<Empty title="A personal welcome starts here" description="Add your first customer to begin arranging their stay."/>}{q.data&&<Pager data={q.data} onPage={setPage}/>} {modal&&<Modal title="Welcome a new customer" onClose={()=>setModal('')}><Form fields={createFields} endpoint="/customers" onSuccess={()=>setModal('')} submit="Create customer"/></Modal>}</>;
}

