'use client';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight,ArrowUpRight,Compass,PlaneLanding,PlaneTakeoff,Users,ClipboardList,CalendarDays,Sun,MapPin,MessageCircle,Clock3 } from 'lucide-react';
import { api,Row,day,time,can,stamp } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { PageTitle,Panel,Status,Empty,Loading,ErrorState } from '@/components/ui';
function RequestRows({items}:{items:Row[]}){return items.length?<div className="compact-list">{items.map(r=><Link key={r.Id} href={'/requests/'+r.Id} className="compact-row"><span className="list-icon"><Compass size={19}/></span><div className="grow"><strong>{r.ServiceName}</strong><small>{r.CustomerName||r.RequestNumber} · {day(r.PreferredDate,true)} · {time(r.PreferredTime)}</small></div><Status value={r.Status}/><ArrowUpRight size={16}/></Link>)}</div>:<Empty title="All clear for now" description="New requests will appear here as your plans take shape."/>;}
export default function Dashboard(){
 const {data:a}=useActor();const q=useQuery({queryKey:['dashboard'],queryFn:()=>api<Row>('/dashboard'),refetchInterval:60000});
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorState error={q.error} retry={()=>q.refetch()}/>;
 const data=q.data!;const staff=can(a,'operations.read');const first=a?.displayName.split(' ')[0];
 return <><PageTitle eyebrow={staff?'AT YOUR SERVICE':'WELCOME TO YOUR ISLAND'} title={staff?'A beautiful day to make it effortless.':'Welcome back, '+first+'.'} description={staff?'Every arrival, every detail, every exceptional experience.':'A little less planning. A little more paradise.'} action={<div className="location-pill"><Sun size={18}/><span>Nassau, The Bahamas<small>{day(data.today)}</small></span></div>}/>
 <section className="hero"><div className="hero-content"><p className="eyebrow">{staff?'THE ART OF ISLAND HOSPITALITY':'YOUR BAHAMAS. BEAUTIFULLY ARRANGED.'}</p><h2>{staff?<>Exceptional stays.<br/>Thoughtful details.</>:<>Your island time<br/>starts here.</>}</h2><p>{staff?'A clear view of what matters, so your team can focus on the people behind every plan.':'From your first arrival to your last sunset, we’ll take care of the details.'}</p><Link className="button light" href={staff?'/operations':'/services'}>{staff?'Open operations board':'Find your next experience'}<ArrowUpRight size={17}/></Link></div><div className="hero-art" aria-hidden="true"/><span className="hero-coordinates">25°04′ N &nbsp; 77°20′ W <span>THE BAHAMAS</span></span></section>
 {staff?<><div className="kpi-grid">{[{name:"Today's arrivals",key:'Arrivals',icon:PlaneLanding},{name:"Today's departures",key:'Departures',icon:PlaneTakeoff},{name:'Active guests',key:'ActiveGuests',icon:Users},{name:'Open requests',key:'OpenRequests',icon:ClipboardList}].map(k=><Link href={k.key==='OpenRequests'?'/requests':'/trips'} className="kpi" key={k.key}><div><span>{k.name}</span><k.icon size={20}/></div><strong>{data.kpis[k.key]}</strong><small>{k.key==='OpenRequests'?data.kpis.PendingReviews+' awaiting a personal touch':'Thoughtfully looked after'}<ArrowUpRight size={13}/></small></Link>)}</div><div className="dashboard-grid"><div><Panel title="Today's operations" action={<Link className="text-link" href="/operations">View board <ArrowRight size={14}/></Link>}><div className="panel-subline"><span className="live-dot"/>{data.kpis.ServicesToday} services today · {data.kpis.ConfirmedServices} confirmed across your workspace</div><RequestRows items={data.operations}/></Panel><Panel title="Recent requests" action={<Link className="text-link" href="/requests">All requests <ArrowRight size={14}/></Link>}><RequestRows items={data.recent}/></Panel></div><div><Panel title="Arriving soon" action={<PlaneLanding size={19}/>}>{data.arrivals.length?<div className="compact-list">{data.arrivals.map((t:Row)=><Link className="arrival-row" key={t.Id} href={'/trips/'+t.Id}><div className="date-square"><strong>{new Date(t.ArrivalDate).getUTCDate()}</strong><span>{new Date(t.ArrivalDate).toLocaleDateString('en-US',{month:'short',timeZone:'UTC'})}</span></div><div><strong>{t.CustomerName}</strong><small>{t.Name}</small><small>{t.Adults+t.Children} guests · {day(t.ArrivalDate,true)}</small></div></Link>)}</div>:<Empty title="Room for new arrivals" description="Upcoming trips will appear here."/>}</Panel><Panel title="Needs a little attention" className="attention-panel">{data.urgent.length?<RequestRows items={data.urgent}/>:<p className="padded muted">Everything is in good hands. No urgent requests.</p>}</Panel></div></div><Panel title="Around the workspace"><div className="activity-strip">{data.activity.map((r:Row,i:number)=><div key={i}><span className="activity-dot"/><strong>{r.Action}</strong><small>{r.ActorName} · {stamp(r.CreatedAt)}</small></div>)}</div></Panel></>:
 <><div className="quick-actions">{[{icon:Compass,label:'Explore services',href:'/services'},{icon:ClipboardList,label:'My requests',href:'/requests'},{icon:CalendarDays,label:'View itinerary',href:'/itinerary'},{icon:MessageCircle,label:'Contact concierge',href:'/messages'}].map(k=><Link key={k.href} href={k.href}><span><k.icon size={20}/></span>{k.label}<ArrowUpRight size={15}/></Link>)}</div><div className="dashboard-grid"><div><Panel title="Your Nassau experience" action={<Link href="/trips" className="text-link">View trip <ArrowRight size={14}/></Link>}>{data.trip?<div className="trip-summary"><p className="eyebrow"><MapPin size={13}/> NASSAU & PARADISE ISLAND</p><h3>{data.trip.Name}</h3><p className="muted">{data.trip.AccommodationName||'Your perfect place is waiting'}</p><div className="trip-facts"><div><PlaneLanding size={18}/><span>ARRIVING<strong>{day(data.trip.ArrivalDate,true)}</strong></span></div><div><PlaneTakeoff size={18}/><span>DEPARTING<strong>{day(data.trip.DepartureDate,true)}</strong></span></div><div><Users size={18}/><span>YOUR PARTY<strong>{data.trip.Adults+data.trip.Children} guests</strong></span></div></div></div>:<Empty title="Let’s plan your Bahamas experience" description="Tell us when you’re arriving, who’s joining and what makes a perfect stay." action={<Link className="button" href="/trips">Create my trip <ArrowRight size={16}/></Link>}/>}</Panel><Panel title="Your requests" action={<Link className="text-link" href="/requests">View all <ArrowRight size={14}/></Link>}><RequestRows items={data.requests}/></Panel></div><div><Panel title="Up next" action={<CalendarDays size={18}/>}>{data.itinerary.length?<div className="mini-timeline">{data.itinerary.map((r:Row)=><Link href="/itinerary" key={r.Id}><span className="timeline-dot"/><small>{day(r.EventDate,true)} · {time(r.EventTime)}</small><strong>{r.Activity}</strong><span><MapPin size={12}/>{r.Location||'Your concierge will share the details'}</span></Link>)}</div>:<Empty title="Good things are on the horizon" description="Confirmed experiences appear here automatically."/>}</Panel><div className="personal-note"><MessageCircle size={24}/><p className="eyebrow">A PERSONAL TOUCH</p><h3>Your wish.<br/>Our pleasure.</h3><p>Something special in mind? Your concierge is here to make it happen.</p><Link href="/messages" className="text-link">Send a little note <ArrowUpRight size={15}/></Link></div></div></div><div className="quiet-note"><Clock3 size={15}/>{data.unread?data.unread+' unread updates are waiting in your notifications.':'Island time, thoughtfully arranged. All experience times are local to The Bahamas.'}</div></>}
 </>;
}

