'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { api,write,can,money,day,Page,Row } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { PageTitle,Panel,Loading,ErrorState,Empty,Pager,Modal,Form,Field,Back,Status } from '@/components/ui';
export default function Finance({mode,id}:{mode:string;id?:string}){
 const actor=useActor();const client=useQueryClient();const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [modal,setModalState]=useState('');const [paymentKey,setPaymentKey]=useState('');const setModal=(value:string)=>{setPaymentKey(crypto.randomUUID());setModalState(value);};const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);
 const path='/'+mode+(id?'/'+id:'?page='+page+'&search='+encodeURIComponent(search));const query=useQuery({queryKey:[path],queryFn:()=>api<Row>(path)});const item=id?query.data:undefined;
 const key=mode==='quotes'?'QuoteNumber':mode==='invoices'?'InvoiceNumber':mode==='payments'?'PaymentNumber':'RefundNumber';
 const writePermission=can(actor.data,mode==='quotes'?'quotes.write':'invoices.write');
 async function change(status:string){setBusy(true);setError(null);try{await write('/'+mode+'/'+id+'/status',{Status:status,Version:item!.Version},'PATCH');await client.invalidateQueries();}catch(err){setError(err as Error);}finally{setBusy(false);}}
 return <>{id&&<Back href={'/'+mode}>All {mode}</Back>}<PageTitle title={item?.[key]||mode[0].toUpperCase()+mode.slice(1)} description={mode==='quotes'?'Review proposed services and agreed pricing.':mode==='invoices'?'Invoices for your bookings, with payment and balance details.':'Recorded payments and refunds.'} action={!id&&writePermission&&['quotes','invoices'].includes(mode)&&<button className="button" onClick={()=>setModal('create')}>New {mode==='quotes'?'quote':'invoice'}</button>}/>{error&&<ErrorState error={error}/>} {query.isPending?<Loading/>:query.error?<ErrorState error={query.error}/>:!id?<><label className="finance-search">Search<input aria-label={'Search '+mode} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><Panel>{query.data?.items.length?<div className="finance-list">{query.data.items.map((row:Row)=><div key={row.Id}><Link href={'/'+(mode==='refunds'?'payments/'+row.PaymentId:mode+'/'+row.Id)}><strong>{row[key]}</strong><small>{row.CustomerName||row.InvoiceNumber||row.PaymentNumber}</small></Link><Status value={row.Status}/><strong>{money(row.Total??row.Amount)} USD</strong></div>)}</div>:<Empty title={'No '+mode+' yet'}/>}</Panel>{query.data&&<Pager data={query.data as Page} onPage={setPage}/>}</>:item&&<article className="finance-document"><div className="finance-document-heading"><div><p className="eyebrow">ISLAND HOST CONCIERGE / ISLAND ONE</p><h2>{mode==='payments'?'Payment receipt':mode==='quotes'?'Quotation':'Invoice'}</h2><p>{item[key]}</p><p>{item.CustomerName}</p><p>{item.TripName}</p></div><Status value={item.Status}/></div>
 {item.Items&&<div className="finance-lines"><div className="finance-line heading"><span>Description</span><span>Qty</span><span>Unit price</span><span>Total</span></div>{item.Items.map((line:Row)=><div className="finance-line" key={line.Id}><span>{line.Description}</span><span>{line.Quantity}</span><span>{money(line.UnitPrice)}</span><strong>{money(line.LineTotal)}</strong></div>)}</div>}
 <dl className="invoice-totals">{(mode==='payments'?[['Amount received',item.Amount],['Refunded',item.RefundedAmount],['Refundable',item.RefundableBalance]]:[['Subtotal',item.Subtotal],['Discount',item.Discount],['Tax',item.Tax],['Fees',item.Fees],['Total',item.Total],...(mode==='invoices'?[['Paid',item.AmountPaid],['Refunded',item.RefundedAmount],['Balance due',item.BalanceDue]]:[])]).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(value)} USD</dd></div>)}</dl>
 <p>{mode==='quotes'?'Valid until: '+day(item.ValidUntil):mode==='payments'?'Received: '+day(item.ReceivedDate):'Due: '+day(item.DueDate)}</p>{item.ProviderReference&&<p>Payment reference: {item.ProviderReference}</p>}{item.Method&&<p>Method: {item.Method}</p>}<p>{item.Terms}</p>{mode==='invoices'&&Number(item.BalanceDue)>0&&<div className="notice"><p>{item.PaymentInstructions||'Contact your concierge to arrange payment using this invoice number.'}</p><p>Online card payment is not available yet. Only valid confirmed bookings can be settled.</p>{item.ItineraryId&&<Link href={'/my-trip?id='+item.ItineraryId}>Review your confirmed bookings</Link>}</div>}
 {mode==='quotes'&&<p className="notice">Approving a quote accepts the proposed price. Availability must still be confirmed before payment.</p>}
 <div className="document-actions"><button className="button secondary" onClick={()=>window.print()}>Print / save PDF</button>{mode==='quotes'&&<>{item.Status==='Draft'&&writePermission&&<><button className="button" disabled={busy} onClick={()=>change('Sent')}>Send quote</button><button className="button secondary" onClick={()=>setModal('edit')}>Edit draft</button></>}{['Sent','Viewed'].includes(item.Status)&&<><button className="button" disabled={busy} onClick={()=>change('Approved')}>Approve quote</button><button className="button secondary" disabled={busy} onClick={()=>change('Rejected')}>Reject quote</button></>}{item.Status==='Approved'&&can(actor.data,'invoices.write')&&<button className="button" onClick={()=>setModal('convert')}>Convert to invoice</button>}</>}
 {mode==='invoices'&&<>{item.Status==='Draft'&&writePermission&&<button className="button" disabled={busy} onClick={()=>change('Issued')}>Issue invoice</button>}{['Draft','Issued','Overdue'].includes(item.Status)&&!Number(item.AmountPaid)&&!Number(item.RefundedAmount)&&writePermission&&<button className="button secondary" disabled={busy} onClick={()=>change('Cancelled')}>Cancel invoice</button>}{['Issued','Partially Paid','Overdue'].includes(item.Status)&&can(actor.data,'payments.write')&&<button className="button" onClick={()=>setModal('payment')}>Record verified payment</button>}{!item.ItineraryId&&writePermission&&<button className="button secondary" onClick={()=>setModal('link')}>Link confirmed bookings</button>}</>}
 {mode==='payments'&&Number(item.RefundableBalance)>0&&can(actor.data,'refunds.write')&&<button className="button" onClick={()=>setModal('refund')}>Record settled refund</button>}</div>
 {!!item.Payments?.length&&<section><h3>Payments</h3>{item.Payments.map((p:Row)=><p key={p.Id}><Link href={'/payments/'+p.Id}>{p.PaymentNumber}</Link> / {money(p.Amount)} / {p.Status}</p>)}</section>}{!!item.Refunds?.length&&<section><h3>Refunds</h3>{item.Refunds.map((r:Row)=><p key={r.Id}>{r.RefundNumber} / {money(r.Amount)} / {r.Reason}</p>)}</section>}</article>}
 {modal&&<Modal title={modal==='payment'?'Record money already received':modal==='refund'?'Record refund already settled':modal==='convert'?'Create invoice':modal==='link'?'Link confirmed bookings':'Prepare '+(mode==='quotes'?'quote':'invoice')} onClose={()=>setModal('')}>{modal==='create'||modal==='edit'?<DocumentEditor mode={mode} initial={modal==='edit'?item:undefined} onDone={()=>setModal('')}/>:modal==='link'?<LinkBookings invoice={item!} onDone={()=>setModal('')}/>:<><p className="muted">{modal==='payment'?'Confirm receipt with your bank or payment terminal before recording. This action does not charge a card.':modal==='refund'?'Confirm the refund has settled outside Island One before recording.':''}</p><Form endpoint={modal==='convert'?'/quotes/'+id+'/invoice':modal==='payment'?'/payments':'/refunds'} extra={modal==='convert'?{Version:item!.Version}:modal==='payment'?{InvoiceId:id,IdempotencyKey:paymentKey}:{PaymentId:id,IdempotencyKey:paymentKey}} initial={modal==='payment'?{Amount:item!.BalanceDue,ReceivedDate:new Date().toLocaleDateString('en-CA',{timeZone:'America/Nassau'})}:modal==='refund'?{Amount:item!.RefundableBalance,RefundedDate:new Date().toLocaleDateString('en-CA',{timeZone:'America/Nassau'})}:{DueDate:new Date().toISOString().slice(0,10)}} fields={modal==='convert'?[{name:'DueDate',label:'Due date',type:'date',required:true}]:[{name:'Amount',label:'Amount (USD)',required:true},...(modal==='payment'?[{name:'Method',label:'Method',type:'select',required:true,options:['Cash','Bank Transfer','Cheque','External Card Terminal','Other'].map(value=>({value,label:value}))}]:[{name:'Reason',label:'Refund reason',type:'textarea',required:true}]),{name:'ProviderReference',label:'Bank / terminal reference',required:true},{name:modal==='payment'?'ReceivedDate':'RefundedDate',label:'Settlement date',type:'date',required:true}]} onSuccess={()=>setModal('')}/></>}</Modal>}</>;
}
function DocumentEditor({mode,initial,onDone}:{mode:string;initial?:Row;onDone:()=>void}){
 const client=useQueryClient();const [lines,setLines]=useState<Row[]>(initial?.Items||[{Description:'',Quantity:1,UnitPrice:'0.00'}]);const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);const options=useQuery({queryKey:['finance-create',mode],queryFn:()=>api<Page>(mode==='quotes'?'/service-requests?limit=100':'/trips?limit=100')});
 return <form className="resource-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);const form=new FormData(e.currentTarget);const body:Row={Items:lines.map(l=>({Description:l.Description,Quantity:Number(l.Quantity),UnitPrice:String(l.UnitPrice),...(l.ServiceId?{ServiceId:l.ServiceId}:{})})),TaxRate:String(form.get('tax')||'0'),Fees:String(form.get('fees')||'0'),Discount:String(form.get('discount')||'0'),Terms:String(form.get('terms')||'')};if(mode==='quotes'){body.RequestId=form.get('parent');body.ValidUntil=form.get('date');if(initial)body.Version=initial.Version;}else{body.TripId=form.get('parent');body.DueDate=form.get('date');}try{await write('/'+mode+(initial?'/'+initial.Id:''),body,initial?'PATCH':'POST');await client.invalidateQueries();onDone();}catch(err){setError(err as Error);}finally{setBusy(false);}}}><div className="form-grid"><label>{mode==='quotes'?'Service request':'Trip'}<select name="parent" required defaultValue={initial?.RequestId||''}>{options.data?.items.map(r=><option key={r.Id} value={r.Id}>{r.RequestNumber||r.Name} - {r.CustomerName||r.ServiceName}</option>)}</select></label><label>{mode==='quotes'?'Valid until':'Due date'}<input name="date" type="date" required defaultValue={initial?.ValidUntil?.slice(0,10)}/></label></div>{options.error&&<ErrorState error={options.error}/>}<h3>Line items</h3>{lines.map((line,index)=><div className="quote-line-editor" key={index}><input aria-label={'Line '+(index+1)+' description'} placeholder="Description" required minLength={2} value={line.Description} onChange={e=>setLines(lines.map((v,n)=>n===index?{...v,Description:e.target.value}:v))}/><input aria-label={'Line '+(index+1)+' quantity'} type="number" required min={1} max={1000} value={line.Quantity} onChange={e=>setLines(lines.map((v,n)=>n===index?{...v,Quantity:Number(e.target.value)}:v))}/><input aria-label={'Line '+(index+1)+' price'} type="number" required min={0} step="0.01" value={line.UnitPrice} onChange={e=>setLines(lines.map((v,n)=>n===index?{...v,UnitPrice:e.target.value}:v))}/><button type="button" className="text-button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,n)=>n!==index))}>Remove</button></div>)}<button type="button" className="text-button" disabled={lines.length>=50} onClick={()=>setLines([...lines,{Description:'',Quantity:1,UnitPrice:'0.00'}])}>Add line</button><div className="form-grid">{[['tax','Tax rate (%)','TaxRate'],['fees','Fees (USD)','Fees'],['discount','Discount (USD)','Discount']].map(([key,label,field])=><label key={key}>{label}<input name={key} type="number" min={0} step="0.01" defaultValue={initial?.[field]||0}/></label>)}<label className="wide">Terms<textarea name="terms" defaultValue={initial?.Terms||''}/></label></div>{error&&<ErrorState error={error}/>}<button className="button" disabled={busy}>{busy?'Saving...':'Save draft'}</button></form>;
}
function LinkBookings({invoice,onDone}:{invoice:Row;onDone:()=>void}){const [ids,setIds]=useState<string[]>([]);const [error,setError]=useState<Error|null>(null);const client=useQueryClient();const plans=useQuery({queryKey:['invoice-plan',invoice.TripId],queryFn:()=>api<Row>('/invoices/'+invoice.Id+'/booking-options')});return <form className="resource-form" onSubmit={async e=>{e.preventDefault();try{await write('/invoices/'+invoice.Id+'/bookings',{ItemIds:ids});await client.invalidateQueries();onDone();}catch(err){setError(err as Error);}}}><p>Selected confirmed totals must exactly match this invoice.</p>{plans.isPending?<Loading/>:plans.error?<ErrorState error={plans.error}/>:plans.data?.Items.map((i:Row)=><label key={i.Id} className="check-label"><input type="checkbox" disabled={!i.Payable} checked={ids.includes(i.Id)} onChange={e=>setIds(e.target.checked?[...ids,i.Id]:ids.filter(v=>v!==i.Id))}/>{i.Activity} / {money(i.ConfirmedPrice)} / {i.BookingStatus}</label>)}{error&&<ErrorState error={error}/>}<button className="button" disabled={!ids.length}>Link bookings</button></form>;}
export function Suppliers(){const [editing,setEditing]=useState<Row|null>(null);const [page,setPage]=useState(1);const actor=useActor();const query=useQuery({queryKey:['vendors',page],queryFn:()=>api<Page>('/vendors?page='+page)});const meta=useQuery({queryKey:['vendor-meta'],queryFn:()=>api<Row>('/vendors/meta')});const fields:Field[]=[{name:'Name',label:'Supplier name',required:true},{name:'Type',label:'Supplier type',type:'select',required:true,options:meta.data?.types.map((value:string)=>({value,label:value}))},{name:'Email',label:'Email',type:'email'},{name:'Phone',label:'Phone'},{name:'UserId',label:'Supplier login account',source:'/vendors/accounts',sourceLabel:'DisplayName'},{name:'Notes',label:'Internal notes',type:'textarea'},{name:'Active',label:'Active',type:'checkbox'}];return <><PageTitle title="Suppliers" description="Manage partners and link their existing Vendor accounts for booking confirmation." action={can(actor.data,'vendors.write')&&<button className="button" onClick={()=>setEditing({Active:true})}>Add supplier</button>}/>{query.isPending?<Loading/>:query.error?<ErrorState error={query.error}/>:<Panel><div className="finance-list">{query.data?.items.map(v=><div key={v.Id}><strong>{v.Name}</strong><span>{v.Type}</span><span>{v.Active?'Active':'Inactive'}</span>{can(actor.data,'vendors.write')&&<button className="text-button" onClick={()=>setEditing(v)}>Edit supplier</button>}</div>)}</div></Panel>}{query.data&&<Pager data={query.data} onPage={setPage}/>} {editing&&<Modal title="Supplier details" onClose={()=>setEditing(null)}><Form fields={fields} initial={editing} endpoint={'/vendors'+(editing.Id?'/'+editing.Id:'')} method={editing.Id?'PATCH':'POST'} onSuccess={()=>setEditing(null)}/></Modal>}</>;}