'use client';
import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { MapPin,ArrowUpRight,Search,Plus,Clock3,Sun } from 'lucide-react';
import { api,write,money,Page,Row } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { readDraft,saveDraft,itemInput,currentPlan } from '@/lib/trip-draft';
import { MarketplaceShell } from '@/components/marketplace-shell';
import { Empty,ErrorState,Loading,Pager,Modal,Back } from '@/components/ui';
export default function Marketplace({id}:{id?:string}){
 const [search,setSearch]=useState('');const [category,setCategory]=useState('');const [destination,setDestination]=useState('Jamaica');const [location,setLocation]=useState('');const [page,setPage]=useState(1);const [adding,setAdding]=useState(false);const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);
 const router=useRouter();const client=useQueryClient();const {data:actor}=useActor();
 const query='/marketplace/listings?search='+encodeURIComponent(search)+'&categoryId='+category+'&destination='+encodeURIComponent(destination)+'&location='+encodeURIComponent(location)+'&page='+page;
 const listings=useQuery({queryKey:[query],queryFn:()=>api<Page>(query),enabled:!id});
 const categories=useQuery({queryKey:['market-categories'],queryFn:()=>api<Row[]>('/marketplace/categories')});
 const detail=useQuery({queryKey:['market-listing',id],queryFn:()=>api<Row>('/marketplace/listings/'+id),enabled:!!id});
 const item=detail.data;
 return <MarketplaceShell>{!id?<><section className="discovery-hero"><div className="discovery-copy"><p className="eyebrow">ISLAND ONE / FIND YOUR JAMAICA</p><h1>Good days start<br/>with a little <em>discovery.</em></h1><p>Find somewhere to stay, something to savour, and a moment worth keeping. Build your trip before you book.</p><Link href="/my-trip" className="button gold">Start planning <ArrowUpRight size={18}/></Link></div><div className="discovery-art" role="img" aria-label="Illustrated Caribbean coastline"/><span className="discovery-caption"><Sun size={20}/> YOUR TIME. YOUR ISLAND.</span></section>
 <div className="market-intro"><div><p className="eyebrow">GO WHERE YOUR CURIOSITY TAKES YOU</p><h2>A whole island of possibilities.</h2></div><p>Save your favourites. We will confirm the bookable details before you pay.</p></div>
 <div className="market-filters"><label className="market-search"><Search size={18}/><input aria-label="Search marketplace" placeholder="A place, a taste, an experience..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Destination<select aria-label="Destination" value={destination} onChange={e=>{setDestination(e.target.value);setPage(1);}}><option value="Jamaica">Jamaica</option><option value="Bahamas">The Bahamas</option><option value="">All destinations</option></select></label><label>Location<input aria-label="Location filter" placeholder="Town or area" value={location} onChange={e=>{setLocation(e.target.value);setPage(1);}}/></label></div>
 <nav className="market-categories" aria-label="Listing categories"><button className={!category?'selected':''} onClick={()=>{setCategory('');setPage(1);}}>All discoveries</button>{categories.data?.map(c=><button key={c.Id} className={category===c.Id?'selected':''} onClick={()=>{setCategory(c.Id);setPage(1);}}>{c.Name}</button>)}</nav>
 {listings.isPending?<Loading/>:listings.error?<ErrorState error={listings.error}/>:!listings.data?.items.length?<Empty title="The next discovery is on its way" description="No published listings match these filters. Try another destination or check back as the collection grows."/>:<div className="market-grid">{listings.data.items.map(s=><article key={s.Id} className="discovery-card"><Link className="discovery-image" href={'/explore/'+s.Id}><Image src={s.Image||'/images/coast.svg'} alt={s.Name} fill unoptimized sizes="(max-width:700px) 100vw, 33vw"/><span>{s.CategoryName}</span></Link><div><p className="market-location"><MapPin size={14}/>{s.Location||s.Destination}</p><Link href={'/explore/'+s.Id}><h3>{s.Name}</h3></Link><p>{s.ShortDescription}</p><div className="discovery-bottom"><span>{money(s.StartingPrice)} <small>{s.PricingType}</small></span><Link href={'/explore/'+s.Id} aria-label={'View '+s.Name}><ArrowUpRight size={22}/></Link></div></div></article>)}</div>}{listings.data&&<Pager data={listings.data} onPage={setPage}/>}</>:detail.isPending?<Loading/>:detail.error?<ErrorState error={detail.error}/>:item&&<><Back href="/explore">Explore the island</Back><div className="listing-detail"><div><div className="listing-cover"><Image src={item.Image||'/images/coast.svg'} alt={item.Name} fill unoptimized priority sizes="(max-width:900px) 100vw, 65vw"/></div><div className="listing-gallery">{gallery(item.Images).map((src,index)=><Image key={src+index} src={src} alt={item.Name+' view '+(index+1)} width={280} height={180} unoptimized/>)}</div><section className="listing-story"><p className="eyebrow">{item.CategoryName} / {item.Destination}</p><h1>{item.Name}</h1><p className="market-location"><MapPin size={17}/>{item.Location||'Location arranged with your concierge'}</p><p className="lead">{item.ShortDescription}</p><p>{item.Description}</p>{item.Amenities&&<><h2>The little extras</h2><p>{item.Amenities}</p></>}{item.VendorName&&<p>Arranged with {item.VendorName}</p>}<h2>Before you book</h2><p>{item.BookingRequirements||'Submit your dates and party size for confirmation.'}</p><p>{item.AvailabilityNotes||'Availability is confirmed personally after you submit your request.'}</p><h2>Changes and cancellation</h2><p>{item.CancellationPolicy||'Ask your concierge for the cancellation terms before confirming your booking.'}</p></section></div><aside className="listing-book"><p className="eyebrow">MAKE ROOM FOR THIS</p><strong>{money(item.StartingPrice)}</strong><span>{item.PricingType} / USD</span><p><Clock3 size={16}/>{item.Duration||'At your own pace'}</p><button className="button full" onClick={()=>setAdding(true)}><Plus size={18}/> Add to My Trip</button><small>{item.Bookable?'Plan now. Availability and the final total are confirmed before payment.':'Save this place to your itinerary. No booking or payment is required.'}</small></aside></div>
 {adding&&<Modal title="Make it part of your trip" onClose={()=>setAdding(false)}><form className="resource-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);const form=new FormData(e.currentTarget);const draft=readDraft();const entry={Id:crypto.randomUUID(),ServiceId:item.Id,Activity:item.Name,Image:item.Image,Bookable:item.Bookable,Location:item.Location,EventDate:String(form.get('date')),EventTime:String(form.get('time')),Quantity:Number(form.get('quantity')),PartySize:Number(form.get('party')),OptionId:String(form.get('option')||''),Notes:String(form.get('notes')||''),BookingStatus:'PLANNED'};try{const selected=actor?.customerId?currentPlan(actor.customerId):'';if(selected)await write('/trip-plans/'+selected+'/items',itemInput(entry));else{if(draft.Items.length>=100)throw new Error('A trip can contain up to 100 items.');draft.Items.push(entry);if(entry.EventDate<draft.ArrivalDate)draft.ArrivalDate=entry.EventDate;if(entry.EventDate>draft.DepartureDate)draft.DepartureDate=entry.EventDate;saveDraft(draft);}await client.invalidateQueries();router.push('/my-trip');}catch(err){setError(err as Error);}finally{setBusy(false);}}}><div className="form-grid"><label>Date<input name="date" type="date" defaultValue={readDraft().ArrivalDate} required/></label><label>Time<input name="time" type="time" defaultValue="10:00" required/></label><label>Quantity<input name="quantity" type="number" defaultValue={1} min={1} max={1000} required/></label><label>Party size<input name="party" type="number" defaultValue={2} min={1} max={200} required/></label>{item.Options?.length>0&&<label>Option<select name="option"><option value="">Standard</option>{item.Options.map((o:Row)=><option key={o.Id} value={o.Id}>{o.Name}</option>)}</select></label>}<label className="wide">Notes<textarea name="notes" maxLength={2000}/></label></div>{error&&<ErrorState error={error}/>}<button className="button" disabled={busy}>{busy?'Adding...':'Add to My Trip'}</button></form></Modal>}</>}</MarketplaceShell>;
}
function gallery(raw:string|null){try{const parsed=JSON.parse(raw||'[]');return Array.isArray(parsed)?parsed.filter((s:unknown)=>typeof s==='string') as string[]:[];}catch{return [];}}