'use client';
import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { ArrowUpRight,LayoutGrid,List,Search,MapPin,Users,CalendarDays,Clock3,Plus } from 'lucide-react';
import { api,write,Page,Row,can,day,time,stamp } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { PageTitle,Panel,Modal,Form,Pager,Empty,Loading,ErrorState,Status,Back,Field } from '@/components/ui';
export default function Requests({board=false,id}:{board?:boolean;id?:string}){
 const {data:a}=useActor();const staff=can(a,'operations.read');const edit=can(a,'requests.write');const client=useQueryClient();
 const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [date,setDate]=useState('');const [category,setCategory]=useState('');const [service,setService]=useState('');const [customer,setCustomer]=useState('');const [sort,setSort]=useState('newest');
 const [action,setAction]=useState('');const [error,setError]=useState<Error|null>(null);const [moving,setMoving]=useState('');
 const path='/service-requests?page='+page+'&limit='+(board?50:20)+'&search='+encodeURIComponent(search)+'&status='+encodeURIComponent(status)+'&date='+date+'&categoryId='+category+'&serviceId='+service+'&customerId='+customer+'&sort='+sort;
 const q=useQuery({queryKey:[path],queryFn:()=>api<Page>(path),enabled:!id,refetchInterval:30000});
 const detail=useQuery({queryKey:['request',id],queryFn:()=>api<Row>('/service-requests/'+id),enabled:!!id});
 const meta=useQuery({queryKey:['request-meta',a?.id],queryFn:()=>api<{statuses:string[];transitions:Record<string,string[]>}>('/service-requests/meta')});
 const cats=useQuery({queryKey:['filter-categories'],queryFn:()=>api<Page>('/service-categories?limit=100'),enabled:!id});
 const services=useQuery({queryKey:['filter-services',category],queryFn:()=>api<Page>('/services?limit=100&categoryId='+category),enabled:!id});
 const customers=useQuery({queryKey:['filter-customers'],queryFn:()=>api<Page>('/customers?limit=100'),enabled:!id&&staff});
 const r=detail.data;
 if(id){
  if(detail.isPending)return <Loading/>;if(detail.error)return <ErrorState error={detail.error}/>;
  const transitions=meta.data?.transitions[r!.Status]||[];
  const fields:Field[]=[...(edit?[{name:'AssignedStaffId',label:'Assigned team member',source:'/users/staff',sourceLabel:'DisplayName'}]:[]),...(action==='Rescheduled'?[{name:'PreferredDate',label:'New date',type:'date',required:true},{name:'PreferredTime',label:'New time',type:'time',required:true}]:[]),{name:'Notes',label:'A note about this update',type:'textarea',hint:'This note is visible to the guest.'}];
  return <><Back href="/requests">All requests</Back><PageTitle eyebrow={r!.RequestNumber} title={r!.ServiceName} description={'Thoughtfully arranged for '+r!.CustomerName} action={<Status value={r!.Status}/>}/><div className="detail-grid"><Panel title="The details"><dl className="detail-facts"><div><dt><CalendarDays size={16}/> Date</dt><dd>{day(r!.PreferredDate)}</dd></div><div><dt><Clock3 size={16}/> Time</dt><dd>{time(r!.PreferredTime)} · Bahamas time</dd></div><div><dt><Users size={16}/> Guests</dt><dd>{r!.Guests}</dd></div><div><dt><MapPin size={16}/> Your concierge</dt><dd>{r!.AssignedStaffName||'Our concierge team'}</dd></div></dl><div className="padded"><h3>Special requirements</h3><p className="muted pre-line">{r!.SpecialRequirements||'No special requirements shared.'}</p><h3>A personal note</h3><p className="muted pre-line">{r!.Notes||'No additional notes.'}</p><Link className="text-link" href={'/trips/'+r!.TripId}>View the trip <ArrowUpRight size={14}/></Link></div>{transitions.length>0&&<div className="status-actions"><h3>{edit?'Keep the experience moving':'Your next step'}</h3><div className="action-wrap">{transitions.map(s=><button key={s} className="button secondary small" onClick={()=>setAction(s)}>{s}</button>)}</div></div>}</Panel><Panel title="Every detail, recorded"><div className="history-list">{r!.History.map((h:Row)=><div key={h.Id}><span className="timeline-dot"/><Status value={h.NewStatus}/><small>{stamp(h.CreatedAt)} · {h.ActorName}</small>{h.PreviousStatus&&<span className="history-from">From {h.PreviousStatus}</span>}{h.Notes&&<p>{h.Notes}</p>}</div>)}</div></Panel></div>{action&&<Modal title={'Update to '+action} onClose={()=>setAction('')}><Form key={action} endpoint={'/service-requests/'+id+'/status'} method="PATCH" extra={{Status:action,Version:r!.Version}} initial={{AssignedStaffId:r!.AssignedStaffId,PreferredDate:r!.PreferredDate,PreferredTime:r!.PreferredTime}} fields={fields} onSuccess={()=>setAction('')} submit="Update request"/></Modal>}</>;
 }
 const reset=()=>setPage(1);
 const groups=[{name:'New',statuses:['Requested']},{name:'Under review',statuses:['Under Review','Quoted','Client Approved','Payment Required','Unavailable','Rescheduled']},{name:'Confirmed',statuses:['Confirmed','Assigned']},{name:'In progress',statuses:['In Progress']},{name:'Completed',statuses:['Completed','Cancelled','Refunded']}];
 return <><PageTitle eyebrow={staff?'THOUGHTFUL COORDINATION':'YOUR CONCIERGE'} title={board?'Every detail, in good hands.':staff?'Service requests':'Your plans, taking shape.'} description={board?'A shared view of every experience, from the first request to the final detail.':staff?'Personal requests. Exceptional follow-through.':'Follow your requests and stay connected with your concierge.'} action={staff?<div className="view-toggle"><Link className={!board?'active':''} href="/requests"><List size={16}/>List</Link><Link className={board?'active':''} href="/operations"><LayoutGrid size={16}/>Board</Link></div>:<Link className="button" href="/services"><Plus size={16}/>Request an experience</Link>}/>
 <div className="filters"><div className="inline-search"><Search size={16}/><input aria-label="Search requests" placeholder="Search requests…" value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></div><select aria-label="Filter status" value={status} onChange={e=>{setStatus(e.target.value);reset();}}><option value="">Every status</option>{meta.data?.statuses.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter category" value={category} onChange={e=>{setCategory(e.target.value);setService('');reset();}}><option value="">All categories</option>{cats.data?.items.map(c=><option key={c.Id} value={c.Id}>{c.Name}</option>)}</select><select aria-label="Filter service" value={service} onChange={e=>{setService(e.target.value);reset();}}><option value="">All services</option>{services.data?.items.map(s=><option key={s.Id} value={s.Id}>{s.Name}</option>)}</select>{staff&&<select aria-label="Filter customer" value={customer} onChange={e=>{setCustomer(e.target.value);reset();}}><option value="">All customers</option>{customers.data?.items.map(c=><option key={c.Id} value={c.Id}>{c.DisplayName}</option>)}</select>}<input type="date" aria-label="Filter preferred date" value={date} onChange={e=>{setDate(e.target.value);reset();}}/><select aria-label="Sort requests" value={sort} onChange={e=>{setSort(e.target.value);reset();}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="date">Experience date</option></select></div>
 {error&&<ErrorState error={error}/>}
 {q.isPending?<Loading/>:q.error?<ErrorState error={q.error}/>:!q.data?.items.length?<Empty title="A little possibility awaits" description="Service requests will appear here as soon as they’re submitted." action={<Link className="button secondary" href="/services">Explore experiences <ArrowUpRight size={16}/></Link>}/>:board?<div className="operations-board">{groups.map(g=><section className="board-column" key={g.name}><h2><i/>{g.name}<span>{q.data.items.filter(r=>g.statuses.includes(r.Status)).length}</span></h2><div className="board-cards">{q.data.items.filter(r=>g.statuses.includes(r.Status)).map(r=><article className="board-card" key={r.Id}><Link href={'/requests/'+r.Id}><p className="eyebrow">{r.RequestNumber}<ArrowUpRight size={13}/></p><h3>{r.ServiceName}</h3><p>{r.CustomerName}</p><div className="board-card-meta"><span><CalendarDays size={13}/>{day(r.PreferredDate,true)}</span><span><Users size={13}/>{r.Guests}</span></div><small>{time(r.PreferredTime)}</small><Status value={r.Status}/></Link>{edit&&(meta.data?.transitions[r.Status]||[]).length>0&&<select aria-label={'Move '+r.RequestNumber} value="" disabled={moving===r.Id} onChange={async e=>{const next=e.target.value;if(!next)return;setMoving(r.Id);setError(null);try{await write('/service-requests/'+r.Id+'/status',{Status:next,Version:r.Version},'PATCH');await client.invalidateQueries();}catch(err){setError(err as Error);}finally{setMoving('');}}}><option value="">Update status…</option>{(meta.data?.transitions[r.Status]||[]).filter(s=>!['Rescheduled','Assigned'].includes(s)).map(s=><option key={s}>{s}</option>)}</select>}</article>)}{!q.data.items.some(r=>g.statuses.includes(r.Status))&&<p className="board-empty">A little breathing room.</p>}</div></section>)}</div>:<Panel><div className="data-table request-table"><div className="table-head"><span>REQUEST & EXPERIENCE</span><span>CUSTOMER</span><span>DATE & TIME</span><span>STATUS</span><span>ASSIGNED TO</span><span/></div>{q.data.items.map(r=><Link className="table-row" href={'/requests/'+r.Id} key={r.Id}><div><small className="eyebrow">{r.RequestNumber}</small><strong>{r.ServiceName}</strong><small>Created {stamp(r.CreatedAt)}</small></div><div><strong>{r.CustomerName}</strong><small>{r.Guests} guests</small></div><div><strong>{day(r.PreferredDate,true)}</strong><small>{time(r.PreferredTime)}</small></div><div><Status value={r.Status}/></div><div className="muted">{r.AssignedStaffName||'Unassigned'}</div><ArrowUpRight size={16}/></Link>)}</div></Panel>}
 {q.data&&<Pager data={q.data} onPage={setPage}/>}<p className="quiet-note">All experience times are local to The Bahamas. {board?'The board shows the current page of requests.':''}</p></>;
}

