'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Plus,Pencil,ShieldCheck,Search } from 'lucide-react';
import { api,Page,Row,stamp } from '@/lib/api';
import { PageTitle,Panel,Modal,Form,Field,Pager,Loading,ErrorState,Empty } from '@/components/ui';
export default function System({page:section}:{page:string}){
 const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [editing,setEditing]=useState<Row|null>(null);
 const path='/'+section+'?page='+page+'&search='+encodeURIComponent(search);
 const q=useQuery({queryKey:[path],queryFn:()=>api<Page|Row[]>(path)});
 const roles=useQuery({queryKey:['roles'],queryFn:()=>api<Row[]>('/roles'),enabled:section==='users'});
 const settings=[{value:'BusinessName',label:'Business name'},{value:'ConciergeEmail',label:'Concierge email'},{value:'ConciergePhone',label:'Concierge phone'},{value:'WelcomeMessage',label:'Welcome message'}];
 const descriptions:Record<string,[string,string]>={users:['The people behind the experience.','Manage team accounts and access to your workspace.'],roles:['The right access. The right people.','Defined responsibilities across your hospitality team.'],settings:['The finishing touches.','Keep your concierge business details current.'],'audit-log':['A clear record of every detail.','An accountable history of changes across your workspace.']};
 const items=Array.isArray(q.data)?q.data:q.data?.items;
 const userFields:Field[]=[{name:'DisplayName',label:'Full name',required:true,max:120},...(!editing?.Id?[{name:'Email',label:'Email address',type:'email',required:true,max:254},{name:'Password',label:'Initial password',type:'password',required:true}]:[{name:'Active',label:'Account active',type:'checkbox'}]),{name:'Roles',label:'Roles',type:'multiselect',required:true,options:roles.data?.filter(r=>r.Name!=='Customer'||editing?.Roles?.includes('Customer')).map(r=>({value:r.Name,label:r.Name})),hint:'Use Ctrl or Command to select more than one role.'}];
 return <><PageTitle eyebrow="YOUR WORKSPACE, WELL KEPT" title={descriptions[section][0]} description={descriptions[section][1]} action={['users','settings'].includes(section)&&<button className="button" onClick={()=>setEditing({Active:true,Roles:[]})}><Plus size={17}/>{section==='users'?'New team member':'Add a setting'}</button>}/>{section==='users'&&<div className="filters"><div className="inline-search"><Search size={16}/><input aria-label="Search users" placeholder="Find a team member…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></div>}
 {q.isPending?<Loading/>:q.error?<ErrorState error={q.error}/>:!items?.length?<Empty title="A clean slate" description="Your workspace details will appear here."/>:section==='roles'?<div className="roles-grid">{items.map(r=><Panel key={r.Id}><div className="role-card"><ShieldCheck size={25}/><h2>{r.Name}</h2><p>{r.Permissions?.length?r.Permissions.join(', '):'Reserved for the next phase'}</p></div></Panel>)}</div>:section==='settings'?<Panel>{items.filter(r=>settings.some(s=>s.value===r.SettingKey)).map(r=><div className="compact-row" key={r.Id}><div className="grow"><strong>{settings.find(s=>s.value===r.SettingKey)?.label}</strong><small>{r.Value}</small></div><button className="icon-button" aria-label={'Edit '+r.SettingKey} onClick={()=>setEditing(r)}><Pencil size={16}/></button></div>)}</Panel>:section==='users'?<Panel><div className="data-table user-table"><div className="table-head"><span>TEAM MEMBER</span><span>ROLE</span><span>STATUS</span><span/></div>{items.map(r=><div className="table-row" key={r.Id}><div><strong>{r.DisplayName}</strong><small>{r.Email}</small></div><div>{r.Roles}</div><span className={'status '+(r.Active?'status-confirmed':'status-cancelled')}>{r.Active?'Active':'Inactive'}</span><button className="icon-button" aria-label={'Edit '+r.DisplayName} onClick={()=>setEditing({...r,Roles:r.Roles.split(', ')})}><Pencil size={16}/></button></div>)}</div></Panel>:<Panel><div className="data-table audit-table"><div className="table-head"><span>ACTION</span><span>BY</span><span>RECORD</span><span>WHEN</span></div>{items.map(r=><div className="table-row" key={r.Id}><div><strong>{r.Action}</strong><small>{r.Metadata&&Object.entries(JSON.parse(r.Metadata)).map(([k,v])=>k+': '+String(v)).join(' · ')}</small></div><div>{r.ActorName||'System'}</div><div>{r.Entity}<small>{r.EntityId}</small></div><div>{stamp(r.CreatedAt)}</div></div>)}</div></Panel>}
 {q.data&&!Array.isArray(q.data)&&<Pager data={q.data} onPage={setPage}/>}
 {editing&&<Modal title={section==='users'?(editing.Id?'Team member access':'Welcome to the team'):'Business details'} onClose={()=>setEditing(null)}><Form fields={section==='users'?userFields:[{name:'SettingKey',label:'Setting',type:'select',required:true,options:settings},{name:'Value',label:'Value',type:'textarea',required:true}]} initial={editing} endpoint={'/'+section+(section==='users'&&editing.Id?'/'+editing.Id:'')} method={section==='users'&&editing.Id?'PATCH':'POST'} onSuccess={()=>setEditing(null)}/></Modal>}</>;
}

