'use client';
import { useEffect,useRef,useState } from 'react';
import { useSearchParams,useRouter } from 'next/navigation';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { Plus,CalendarDays,Users,MapPin,ArrowRight,Pencil } from 'lucide-react';
import { api,write,money,day,Row } from '@/lib/api';
import { useActor } from '@/lib/providers';
import { readDraft,saveDraft,clearDraft,freshDraft,itemInput,planInput,currentPlan,selectPlan } from '@/lib/trip-draft';
import { MarketplaceShell,BookingBadge } from '@/components/marketplace-shell';
import { ErrorState,Loading,Empty,Modal,Form,Field } from '@/components/ui';
const itemFields:Field[]=[{name:'EventDate',label:'Date',type:'date',required:true},{name:'EventTime',label:'Time',type:'time',required:true},{name:'Quantity',label:'Quantity',type:'number',min:1,max:1000,required:true},{name:'PartySize',label:'Party size',type:'number',min:1,max:200,required:true},{name:'Pickup',label:'Pickup',max:300},{name:'Dropoff',label:'Drop-off',max:300},{name:'Notes',label:'Notes',type:'textarea',max:2000}];
export default function TripBuilder(){
 const actor=useActor();const client=useQueryClient();const params=useSearchParams();const router=useRouter();
 const [draft,setDraft]=useState<Row|null>(null);const [id,setId]=useState('');const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<Row|null>(null);const [planEdit,setPlanEdit]=useState(false);const [newPlan,setNewPlan]=useState(false);const [selected,setSelected]=useState<string[]>([]);const imported=useRef(false);const checkoutKey=useRef('');
 useEffect(()=>{setDraft(readDraft());},[]);
 const plans=useQuery({queryKey:['my-trip-plans'],queryFn:()=>api<Row[]>('/trip-plans'),enabled:!!actor.data?.customerId});
 useEffect(()=>{if(actor.data?.customerId&&!id){const chosen=params.get('id')||currentPlan(actor.data.customerId)||plans.data?.[0]?.Id||'';if(chosen)setId(chosen);}},[actor.data,params,plans.data,id]);
 useEffect(()=>{
  if(!draft||!actor.data?.customerId||imported.current||!draft.Items.length)return;
  imported.current=true;setBusy(true);
  write<Row>('/trip-plans/import',{...planInput(draft),GuestReference:draft.GuestReference,Items:draft.Items.map(itemInput)}).then(result=>{selectPlan(actor.data!.customerId!,result.Id);setId(result.Id);clearDraft();setDraft(freshDraft());return client.invalidateQueries();}).catch(err=>{setError(err);}).finally(()=>setBusy(false));
 },[draft,actor.data,client]);
 const plan=useQuery({queryKey:['trip-plan',id],queryFn:()=>api<Row>('/trip-plans/'+id),enabled:!!id&&!!actor.data?.customerId,refetchInterval:30000});
 useEffect(()=>{if(plan.data?.Id&&actor.data?.customerId)selectPlan(actor.data.customerId,plan.data.Id);},[plan.data?.Id,actor.data?.customerId]);
 useEffect(()=>{setSelected([]);checkoutKey.current='';},[id]);
 const checkout=useQuery({queryKey:['booking-checkout',id],queryFn:()=>api<Row>('/trip-plans/'+id+'/checkout'),enabled:!!id&&!!actor.data?.customerId,refetchInterval:30000});
 const options=useQuery({queryKey:['edit-booking-options',edit?.ServiceId],queryFn:()=>api<Row>('/services/'+edit!.ServiceId),enabled:!!edit?.ServiceId&&!!actor.data?.customerId});
 const member=!!actor.data?.customerId;const current=member?plan.data:draft;const items:Row[]=current?.Items||[];const payable:Row[]=checkout.data?.Items.filter((i:Row)=>i.Payable)||[];
 const refresh=async()=>{await client.invalidateQueries();window.dispatchEvent(new Event('islandone-trip'));};
 async function action(item:Row,status:string,notes?:string){setBusy(true);setError(null);try{await write('/bookings/'+item.Id+'/status',{Status:status,Version:item.Version,Notes:notes},'PATCH');await refresh();}catch(err){setError(err as Error);}finally{setBusy(false);}}
 function saveLocal(next:Row){saveDraft(next);setDraft({...next});}
 return <MarketplaceShell><div className="builder-heading"><div><p className="eyebrow">A LITTLE STRUCTURE. ROOM FOR SPONTANEITY.</p><h1>My Trip</h1><p>Make a plan you love. Book only when the details are confirmed.</p></div><Link className="button secondary" href="/explore"><Plus size={17}/> Add a discovery</Link></div>
 {error&&<ErrorState error={error} retry={()=>{setError(null);imported.current=false;setDraft(readDraft());void refresh();}}/>}
 {!member&&!actor.isPending&&<div className="guest-note"><div><strong>Your trip is saved on this device.</strong><p>Sign in to keep this itinerary and submit booking requests. Your plans come with you.</p></div><Link className="button" href="/login?next=/my-trip">Sign in &amp; keep my trip <ArrowRight size={16}/></Link></div>}
 {member&&<div className="trip-selector"><label>Saved trips<select aria-label="Saved trips" value={id} onChange={e=>{setId(e.target.value);selectPlan(actor.data!.customerId!,e.target.value);setSelected([]);checkoutKey.current='';}}><option value="">Choose a trip</option>{plans.data?.map(p=><option key={p.Id} value={p.Id}>{p.Name}</option>)}</select></label><button className="text-button" onClick={()=>{setNewPlan(true);setPlanEdit(true);}}>Plan another trip</button></div>}
 {busy&&<p role="status">Saving your trip...</p>}{member&&plan.error&&<ErrorState error={plan.error}/>}
 {member&&id&&plan.isPending?<Loading/>:current?<><section className="trip-summary"><div><p className="eyebrow">{current.Destination||'Your island'}</p><h2>{current.Name}</h2><div className="trip-facts"><span><CalendarDays size={16}/>{day(current.ArrivalDate,true)} - {day(current.DepartureDate,true)}</span><span><Users size={16}/>{Number(current.Adults)+Number(current.Children)} travelers</span></div></div><button className="text-button" onClick={()=>setPlanEdit(true)}><Pencil size={16}/> Edit trip</button></section>
 <div className="builder-grid"><section className="trip-timeline" aria-label="Trip timeline">{!items.length?<Empty title="Leave room for a little adventure" description="Browse the island and add your first place or experience." action={<Link href="/explore" className="button">Explore Jamaica</Link>}/>:items.map(item=><article className={'trip-item '+(!item.Active&&member?'trip-item-inactive':'')} key={item.Id}><div className="trip-item-date"><strong>{day(item.EventDate,true)}</strong><span>{item.EventTime}</span></div><div className="trip-item-content"><BookingBadge status={item.EffectiveStatus||item.BookingStatus||'PLANNED'}/><h3>{item.Activity}</h3><p><MapPin size={14}/>{item.Location||'To be arranged'}</p><p>{item.PartySize||1} travelers / Quantity {item.Quantity||1}</p>{item.Notes&&<p>{item.Notes}</p>}{item.ConfirmedPrice!=null&&<p className="confirmed-total">Confirmed total: {money(item.ConfirmedPrice)} USD</p>}{item.ConfirmationReference&&<small>Reference: {item.ConfirmationReference}</small>}{item.ConfirmationExpiresAt&&<small>Confirmation expires: {new Date(item.ConfirmationExpiresAt).toLocaleString()}</small>}{item.ConfirmationConditions&&<p>{item.ConfirmationConditions}</p>}{item.PaymentStatus&&item.PaymentStatus!=='UNPAID'&&<p>Payment: {item.PaymentStatus.replaceAll('_',' ').toLowerCase()}{item.CheckoutInvoiceId&&<> / <Link href={'/invoices/'+item.CheckoutInvoiceId}>View invoice</Link></>}</p>}
 {(item.Active||!member)&&!['CANCELLED','COMPLETED'].includes(item.BookingStatus)&&<div className="trip-item-actions"><button className="text-button" disabled={busy} onClick={()=>setEdit(item)}>Edit details</button>{member&&item.ServiceId&&item.Bookable!==false&&['PLANNED','CHANGE_REQUESTED','REJECTED','EXPIRED'].includes(item.EffectiveStatus||item.BookingStatus)&&<button className="button small" disabled={busy} onClick={()=>action(item,'PENDING_CONFIRMATION')}>{item.BookingStatus==='CHANGE_REQUESTED'?'Request reconfirmation':'Request confirmation'}</button>}<button className="text-button" disabled={busy} onClick={()=>member?action(item,'CANCELLED','Cancelled by customer.'):saveLocal({...draft!,Items:draft!.Items.filter((i:Row)=>i.Id!==item.Id)})}>{member?'Cancel item':'Remove'}</button></div>}</div></article>)}</section>
 <aside className="checkout-panel"><p className="eyebrow">CONFIRMED &amp; READY</p><h2>Your checkout</h2><p>Only confirmed, unexpired, unpaid bookings can be selected.</p>{checkout.error&&<ErrorState error={checkout.error}/>} {payable.length?payable.map(item=><label className="checkout-choice" key={item.Id}><input type="checkbox" checked={selected.includes(item.Id)} onChange={e=>{setSelected(e.target.checked?[...selected,item.Id]:selected.filter(v=>v!==item.Id));checkoutKey.current='';}}/><span>{item.Activity}<strong>{money(item.ConfirmedPrice)}</strong></span></label>):<p className="muted">Your confirmed bookings will appear here when they are ready for payment.</p>}<div className="checkout-total"><span>Selected total</span><strong>{money(payable.filter(i=>selected.includes(i.Id)).reduce((sum,i)=>sum+Number(i.ConfirmedPrice),0))}<small> USD</small></strong></div><button className="button full" disabled={busy||!selected.length||!member} onClick={async()=>{setBusy(true);setError(null);try{checkoutKey.current||=crypto.randomUUID();const invoice=await write<Row>('/trip-plans/'+id+'/checkout',{ItemIds:selected,IdempotencyKey:checkoutKey.current});await refresh();router.push('/invoices/'+invoice.Id);}catch(err){setError(err as Error);await refresh();}finally{setBusy(false);}}}>Continue to invoice <ArrowRight size={16}/></button><small>Online card payment is not available yet. Your concierge will help arrange payment against the invoice.</small><hr/><h3>Still in your plans</h3><p>{items.filter(i=>['PLANNED','PENDING_CONFIRMATION','RECONFIRMING','CHANGE_REQUESTED'].includes(i.BookingStatus)).length} items are awaiting a request or confirmation.</p><p>{items.filter(i=>['REJECTED','CANCELLED','EXPIRED'].includes(i.EffectiveStatus||i.BookingStatus)).length} items are unavailable, cancelled or expired. These are excluded from checkout.</p></aside></div></>:!actor.isPending&&member&&<Empty title="Start your next island story" description="Create a trip, then add places and experiences." action={<button className="button" onClick={()=>setPlanEdit(true)}>Create trip</button>}/>}
 {planEdit&&<Modal title={current&&!newPlan?'Your trip details':'Plan a new trip'} onClose={()=>{setPlanEdit(false);setNewPlan(false);}}><PlanForm initial={newPlan?freshDraft():current||freshDraft()} onSave={async values=>{setError(null);if(member){const saved=await write<Row>('/trip-plans'+(id&&!newPlan?'/'+id:''),values,id&&!newPlan?'PATCH':'POST');setId(saved.Id);selectPlan(actor.data!.customerId!,saved.Id);await refresh();}else saveLocal({...draft!,...values});setPlanEdit(false);setNewPlan(false);}}/></Modal>}
 {edit&&<Modal title="Refine your plans" onClose={()=>setEdit(null)}>{member?<><p className="muted">Changing dates, options, party size or transport details requires a new confirmation.</p><Form initial={edit} endpoint={'/bookings/'+edit.Id} method="PATCH" extra={{Version:edit.Version}} fields={[...itemFields,...(options.data?.Options?.length?[{name:'OptionId',label:'Service option',type:'select',options:options.data.Options.map((o:Row)=>({value:o.Id,label:o.Name}))}]:[])]} onSuccess={()=>{setEdit(null);void refresh();}}/></>:<LocalItemForm initial={edit} onSave={value=>{saveLocal({...draft!,Items:draft!.Items.map((i:Row)=>i.Id===edit.Id?{...i,...value}:i)});setEdit(null);}}/>}</Modal>}
 </MarketplaceShell>;
}
function PlanForm({initial,onSave}:{initial:Row;onSave:(value:Row)=>Promise<void>}){const [error,setError]=useState<Error|null>(null);const [busy,setBusy]=useState(false);return <form className="resource-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const input=Object.fromEntries(new FormData(e.currentTarget));await onSave(planInput(input));}catch(err){setError(err as Error);}finally{setBusy(false);}}}><div className="form-grid">{[{key:'Name',label:'Trip name',type:'text'},{key:'Destination',label:'Destination',type:'text'},{key:'ArrivalDate',label:'Start date',type:'date'},{key:'DepartureDate',label:'End date',type:'date'},{key:'Adults',label:'Adults',type:'number'},{key:'Children',label:'Children',type:'number'}].map(f=><label key={f.key}>{f.label}<input aria-label={f.label} name={f.key} type={f.type} defaultValue={f.type==='date'?initial[f.key]?.slice(0,10):initial[f.key]} required min={f.key==='Adults'?1:0} max={f.type==='number'?100:undefined} maxLength={f.key==='Name'?120:100}/></label>)}</div>{error&&<ErrorState error={error}/>}<button className="button" disabled={busy}>{busy?'Saving...':'Save trip'}</button></form>;}
function LocalItemForm({initial,onSave}:{initial:Row;onSave:(value:Row)=>void}){return <form className="resource-form" onSubmit={e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.currentTarget));onSave({...input,Quantity:Number(input.Quantity),PartySize:Number(input.PartySize)});}}><div className="form-grid">{itemFields.map(f=><label key={f.name}>{f.label}<input name={f.name} aria-label={f.label} type={f.type==='textarea'?'text':f.type||'text'} defaultValue={initial[f.name]||''} required={f.required} min={f.min} max={f.type==='number'?f.max:undefined}/></label>)}</div><button className="button">Save details</button></form>;}